import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import MobileNavBarProvider from "@/context/MobileNavBarProvider";
import { OurThemeProvider } from "@/context/ThemeProvider";
import WebSocketClientProvider from "@/context/WebSocketClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WebSocketClientProvider>
          <OurThemeProvider>
            <MobileNavBarProvider>
              <Toaster richColors position="top-center" />
              {children}
            </MobileNavBarProvider>
          </OurThemeProvider>
        </WebSocketClientProvider>
      </body>
    </html>
  );
}
