import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import MobileNavBarProvider from "@/context/MobileNavBarProvider";
import ReactQueryClientProvider from "@/context/QueryClientProvider";
import { Analytics } from "@vercel/analytics/react"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClientProvider>
         
            <MobileNavBarProvider>
              <Toaster richColors position="top-center" />
              {children}
              <Analytics />
            </MobileNavBarProvider>
       
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
